"""Initial migration

Revision ID: 9f96a3f848ab
Revises: 20c71df527b4
Create Date: 2024-07-15 10:40:08.489377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f96a3f848ab'
down_revision: Union[str, None] = '20c71df527b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserved_rooms', 'commentary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserved_rooms', 'commentary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
